/* NTS storefront prototype. Cart is local-only until a secure backend is connected. */
const PRICE = 2999;
const COLOURS = ['Black','Off-White','White','Olive'];
const STORAGE_KEY = 'nts-system01-cart-v1';
let cart = loadCart();
const $ = (selector, root=document) => root.querySelector(selector);
const $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
function loadCart(){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(value)?value.filter(x=>COLOURS.includes(x.colour)&&Number.isInteger(x.qty)&&x.qty>0):[]}catch{return []}}
function saveCart(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(cart))}catch{} renderCart()}
function money(n){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)}
function notify(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.classList.remove('show'),2200)}
function addToCart(colour){const item=cart.find(x=>x.colour===colour&&x.size==='M');if(item)item.qty++;else cart.push({colour,size:'M',qty:1});saveCart();notify(`${colour} added to your bag. Size M selected as a preview.`)}
function renderCart(){const count=cart.reduce((n,x)=>n+x.qty,0),total=cart.reduce((n,x)=>n+x.qty*PRICE,0);$('#cart-count').textContent=count;$('#drawer-count').textContent=`(${count})`;$('#subtotal').textContent=money(total);$('#checkout-button').disabled=count===0;const list=$('#cart-items');if(!count){list.innerHTML='<p class="empty-cart">Your bag is currently empty.</p>';return}list.innerHTML=cart.map((item,index)=>`<div class="cart-row"><div class="cart-thumb" style="background:${({'Black':'#252620','Off-White':'#e3dfd4','White':'#f8f7f2','Olive':'#747a58'})[item.colour]};color:${item.colour==='Black'?'#f0efe9':'#171815'}">N</div><div><h3>System 01 / ${item.colour}</h3><p>SIZE ${item.size} · ${money(PRICE)}</p><div class="qty-control"><button data-qty="minus" data-index="${index}" aria-label="Decrease quantity">−</button><span>${item.qty}</span><button data-qty="plus" data-index="${index}" aria-label="Increase quantity">+</button></div><button class="remove-item" data-remove="${index}">REMOVE</button></div><strong class="price">${money(item.qty*PRICE)}</strong></div>`).join('')}
function openCart(){ $('#overlay').hidden=false;$('#cart-drawer').classList.add('open');$('#cart-drawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeCart(){ $('#overlay').hidden=true;$('#cart-drawer').classList.remove('open');$('#cart-drawer').setAttribute('aria-hidden','true');document.body.style.overflow=''}
$$('[data-add]').forEach(button=>button.addEventListener('click',()=>addToCart(button.dataset.add)));
$$('[data-quick-add]').forEach(button=>button.addEventListener('click',()=>addToCart(button.dataset.quickAdd)));
$$('[data-swatch]').forEach(button=>button.addEventListener('click',()=>{const card=button.closest('.product-card');const colour=button.dataset.swatch;card.dataset.colour=colour;$$('.swatch',card).forEach(s=>s.classList.toggle('active',s===button));const title=$('h2',card);title.textContent=`System 01 / ${colour}`;const desc=$('.product-meta p',card);desc.textContent=`Relaxed fit · ${colour}`;const img=$('.product-image',card);img.className=`product-image ${({'Black':'image-black','Off-White':'image-offwhite','White':'image-white','Olive':'image-olive'})[colour]}`;img.dataset.quickAdd=colour;img.setAttribute('aria-label',`Choose ${colour} tee`);$('.add-button',card).dataset.add=colour}));
$('#open-cart').addEventListener('click',openCart);$('#close-cart').addEventListener('click',closeCart);$('#overlay').addEventListener('click',closeCart);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCart()});
$('#cart-items').addEventListener('click',e=>{const qty=e.target.closest('[data-qty]');const remove=e.target.closest('[data-remove]');if(qty){const i=Number(qty.dataset.index);if(!cart[i])return;if(qty.dataset.qty==='plus')cart[i].qty++;else cart[i].qty--;if(cart[i].qty<1)cart.splice(i,1);saveCart()}if(remove){cart.splice(Number(remove.dataset.remove),1);saveCart()}});
$('#checkout-button').addEventListener('click',()=>notify('Checkout is not connected yet. Next milestone: secure backend + payment integration.'));
$('#size-guide').addEventListener('click',()=>$('#size-dialog').showModal());$('#close-size').addEventListener('click',()=>$('#size-dialog').close());
$('#signup-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,status=$('#signup-status'),button=$('button[type="submit"]',form);button.disabled=true;status.textContent='Submitting…';try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Submission failed');status.textContent='You’re on the list. We’ll be in touch.';form.reset()}catch{status.textContent='Could not submit right now. Please try again in a moment.'}finally{button.disabled=false}});
renderCart();
